'use strict';
const fs = require('fs');
const path = require('path');
const source = path.resolve(__dirname, '..', 'shared', 'ads-design-rules.js');
const outputDirectory = path.join(__dirname, 'shared');
const output = path.join(outputDirectory, 'ads-design-rules.js');
if (!fs.existsSync(source)) throw new Error('Shared Ads Design rules source is missing: ' + source);
fs.mkdirSync(outputDirectory, { recursive:true });
fs.copyFileSync(source, output);
console.log('Packaged shared Ads Design rules at functions/shared/ads-design-rules.js');
