// Generated read-only browser projection; canonical CJS modules remain authoritative.
import fs from 'node:fs';
import taxonomy from '../shared/canonical-taxonomy-core.js';
import data from '../shared/canonical-taxonomy-data.js';
import mapping from '../shared/taxonomy-legacy-mapping.js';
const categories=taxonomy.listCategories().map(c=>({...c,definitions:taxonomy.isCanonicalProductCategory(c.id)?data.PRODUCT_TYPE_DEFINITIONS[c.id]||{}:{}}));
const content='// GENERATED by tools/build_product_schema_bridge.mjs — do not edit.\nexport default '+JSON.stringify({categories,mappings:mapping.DIRECT_CATEGORY_MAPPINGS,branchContexts:data.BRANCH_CONTEXT_CLASSIFICATIONS,productLeaves:Object.fromEntries(categories.filter(c=>taxonomy.isCanonicalProductCategory(c.id)).map(c=>[c.id,(data.PRODUCT_SUBCATEGORIES[c.id]||data.CATEGORY_CLASSIFICATIONS[c.id]?.productBranches||[]).filter(leaf=>!data.BRANCH_CONTEXT_CLASSIFICATIONS[c.id]?.[leaf]||data.BRANCH_CONTEXT_CLASSIFICATIONS[c.id][leaf]==='PRODUCT')]))})+';\n';
const url=new URL('../shared/product-taxonomy-browser.mjs',import.meta.url);
if(process.argv.includes('--check')){if(!fs.existsSync(url)||fs.readFileSync(url,'utf8')!==content)throw Error('Taxonomy projection drift: run node tools/build_product_schema_bridge.mjs');console.log('PASS taxonomy browser projection matches canonical authority');}else fs.writeFileSync(url,content);
