import fs from 'node:fs';import crypto from 'node:crypto';import vm from 'node:vm';import data from '../shared/canonical-taxonomy-data.js';import projection from '../shared/product-taxonomy-browser.mjs';import {getProductSuggestions,getSellerSubcategories} from '../shared/product-taxonomy-bridge.mjs';// Optional reviewed overlay — an open blocker while the module is uncommitted.
// Not reconstructed here; absence degrades alias reconciliation and is reported.
let reviewedLiveLeafAliases=[],overlayDegraded=true;
try{({reviewedLiveLeafAliases}=await import('../shared/product-schema-refinements.mjs'));overlayDegraded=false;}catch{reviewedLiveLeafAliases=[];}
// AUDIT INPUT CONTRACT
//  committed source : shared/*, js/app/*, docs/taxonomy/mission/all-leaf-browser.json,
//                     docs/taxonomy/mission/food-changes.json
//  required LOCAL input (gitignored by payload policy, never auto-committed):
//                     docs/taxonomy/mission/execution-queue.json
//                     an audit baseline file (see --baseline below)
//  optional overlays : shared/product-schema-refinements.mjs (currently an open blocker)
const root='docs/taxonomy/mission';
const requireLocal=(p,why)=>{if(!fs.existsSync(p))throw Error('Missing REQUIRED LOCAL INPUT: '+p+'\n'+why+'\nThis file is intentionally gitignored by the GitHub payload policy and is not part of committed source. Restore it locally; do not commit it unless explicitly instructed.');return p;};
const queue=JSON.parse(fs.readFileSync(requireLocal(root+'/execution-queue.json','It holds the per-leaf research queue and candidate excerpts for all 743 product leaves.'))),ui=JSON.parse(fs.readFileSync(root+'/all-leaf-browser.json')),changes=JSON.parse(fs.readFileSync(root+'/food-changes.json'));const bootstrap=fs.readFileSync('js/app/00-bootstrap.js','utf8'),ctx={skh:{}};vm.runInNewContext(bootstrap.slice(bootstrap.indexOf('skh.advancedCategories ='),bootstrap.indexOf('\n',bootstrap.indexOf('};',bootstrap.indexOf('skh.advancedCategories =')))),ctx);const live=ctx.skh.advancedCategories;
const leaves=queue.map(row=>{
 const categoryId=row.categoryId,leaf=row.leaf,definition=data.PRODUCT_TYPE_DEFINITIONS[categoryId]?.[leaf]||null,schema=getProductSuggestions(categoryId,leaf);
 const exactLiveMatches=Object.entries(live).flatMap(([parent,v])=>Object.keys(v.subcategories||{}).filter(l=>l===leaf&&projection.mappings[parent]===categoryId).map(l=>({parent,leaf:l}))),approvedAliases=reviewedLiveLeafAliases.filter(a=>a[2]===categoryId&&a[3]===leaf).map(a=>({liveParent:a[0],liveLeaf:a[1]}));
 const change=changes.find(c=>c.categoryId===categoryId&&c.leaf===leaf);
 return {categoryId,canonicalCategory:data.CATEGORY_REGISTRY.find(c=>c.id===categoryId).displayName,leaf,reviewStatus:change?'PARTIAL_SEMANTIC_REVIEW':'RETRIEVED_NOT_ADJUDICATED',exhaustiveReview:false,finalStatus:'NOT COMPLETED',definition,definitionStatus:!definition?'DEFAULT_ONLY':definition.status==='PARTIAL'?'PARTIAL':'EXACT_REQUIRES_FIELD_REVIEW',externalEvidence:change?change.source:row.candidatePassages,variant:{sourceRule:definition?.variantRule||null,classification:'NOT_CERTIFIED_BY_THIS_MISSION',reason:'Existing positive rules retained where supported; no exhausted all-tier review claimed'},attributes:schema.attributes,selectors:schema.options,filters:{references:schema.filterMappings||[],attributeReferences:schema.filters},features:{suggestions:schema.features,scope:'Seller confirmed; not assertions about listed product'},additionalInfo:schema.additionalInfo,units:{suggestions:schema.suggestedUnits,conversion:'NO_NEW_CONVERSION',sourceReview:'INCOMPLETE; customs unit not selling unit'},media:{schema:schema.mediaRequirements,review:'No newly required photos; empty guidance not evidence of exhaustive search'},mapping:{reviewStatus:'REVIEWED_REPOSITORY_ROUTING',canonicalPath:[categoryId,leaf],canonicalSellerRoute:{parent:categoryId,leaf,available:getSellerSubcategories(categoryId,live).includes(leaf)},exactLiveMatches,approvedAliases,noAliasRequired:true,noAliasReason:'Explicit canonical-ID seller route; does not assert every legacy label is semantically mapped',unresolvedLegacyMapping:!exactLiveMatches.length&&!approvedAliases.length},UI:ui.results.find(r=>r.categoryId===categoryId&&r.leaf===leaf),blockers:{research:'Authoritative corpus candidate retrieval is not exhausted source search or semantic adjudication',production:'Live auth/storage/callables E2E not run',fullCertification:true}};
});
// Portable baseline resolution — no machine-specific absolute path.
// Order: --baseline=<path> CLI flag, then SOKOHAI_AUDIT_BASELINE env var, then the
// repository-relative default. Works on Windows, Linux and a clean clone.
const baselineArg=process.argv.find(a=>a.startsWith('--baseline='))?.slice('--baseline='.length);
const baselineCandidates=[baselineArg,process.env.SOKOHAI_AUDIT_BASELINE,root+'/authorized-update-baseline.json'].filter(Boolean);
const baselinePath=baselineCandidates.find(p=>fs.existsSync(p));
if(!baselinePath)throw Error('Audit baseline not found. This file supplies every "before" hash and is LOCAL INPUT, not committed source.\nProvide it with one of:\n  node tools/build_taxonomy_mission_audit.mjs --baseline=<path>\n  SOKOHAI_AUDIT_BASELINE=<path> node tools/build_taxonomy_mission_audit.mjs\n  place it at '+root+'/authorized-update-baseline.json\nSearched: '+baselineCandidates.join(', '));
const baseline=JSON.parse(fs.readFileSync(baselinePath));const hashes=Object.entries(baseline.hashes).map(([file,before])=>({file,before,after:crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex'),scope:file==='shared/canonical-taxonomy-data.js'?'CANONICAL':'PROTECTED_EXECUTION_OR_CORE'})).map(r=>({...r,changed:r.before!==r.after}));
const categories=data.CATEGORY_REGISTRY.map(c=>({id:c.id,name:c.displayName,kind:c.kind,productLeaves:leaves.filter(r=>r.categoryId===c.id).length,reviewStatus:leaves.some(r=>r.categoryId===c.id)?'RESEARCH_INCOMPLETE':'NON_PRODUCT_BOUNDARY'}));
const master={status:'NOT COMPLETED',counts:{categories:categories.length,canonicalLeaves:750,productLeaves:leaves.length,contextLeaves:7,fullSemanticCertification:0,corpusRetrievalPackets:queue.length,exhaustivelyReviewed:0,newPartialSemanticAmendments:changes.length,browserLeafPathsPassed:ui.results.filter(r=>r.status==='PASS').length},categories,leaves};
fs.writeFileSync(root+'/master-tracking.json',JSON.stringify(master,null,2));fs.writeFileSync(root+'/authority-hashes.json',JSON.stringify(hashes,null,2));fs.writeFileSync(root+'/blockers.json',JSON.stringify(leaves.map(({categoryId,leaf,reviewStatus,blockers})=>({categoryId,leaf,reviewStatus,...blockers})),null,2));
for(const c of changes)c.tests='PASS: test_canonical_controlled_changes; test_taxonomy_mission_contract; test_final_product_taxonomy_verification; all-leaf browser 743/743. Supplemental sentinel change in food-state-compatibility.json';fs.writeFileSync(root+'/food-changes.json',JSON.stringify(changes,null,2));
console.log(master.counts);console.log('unchanged protected',hashes.filter(r=>r.scope!=='CANONICAL'&&!r.changed).length);
