import assert from 'node:assert/strict';
import pkg from '../shared/canonical-taxonomy-core.js';
const { listCategories, getCategory, getSubcategories, getOverlay, getFallbackDefinition, validateCategoryRegistry, validateHierarchy } = pkg;
const result = validateCategoryRegistry(); assert.equal(result.ok, true, result.errors.join('; '));
assert.equal(listCategories().length, 44);
for (let n = 1; n <= 44; n++) assert.equal(getCategory(`CAT-${String(n).padStart(2,'0')}`).number, n);
assert.equal(getCategory('CAT-16').displayName, 'Usafiri & Logistics');
for (let n = 17; n <= 26; n++) assert.equal(getCategory(`CAT-${n}`).kind, 'SERVICE_DOMAIN');
assert.equal(getCategory('CAT-39').kind, 'OVERLAY');
assert.equal(getCategory('CAT-40').kind, 'OVERLAY');
assert.equal(getCategory('CAT-41').kind, 'OVERLAY');
assert.equal(getCategory('CAT-42').displayName, 'Ardhi & Property');
assert.equal(getCategory('CAT-43').displayName, 'Madini, Mawe & Resources');
assert.equal(getCategory('CAT-44').displayName, 'OTHER / HAIPO HAPA');
assert.ok(getSubcategories('CAT-01').includes('Nafaka, Unga & Mikunde'));
assert.ok(getSubcategories('CAT-03').includes('Agricultural Bulk Commodities'));
assert.ok(getSubcategories('CAT-43').includes('Gemstones'));
assert.equal(getOverlay('CAT-39').purpose, 'CROSS_CATEGORY_CONDITION_DISCOVERY');
assert.equal(getOverlay('CAT-40').purpose, 'CROSS_CATEGORY_COMMERCIAL_DISCOVERY');
assert.equal(getOverlay('CAT-41').purpose, 'CROSS_CATEGORY_TRADE_DISCOVERY');
assert.deepEqual(getFallbackDefinition().allowedLevels, ['CATEGORY','SUBCATEGORY','PRODUCT_TYPE','ATTRIBUTE_VALUE','OPTION_VALUE','VARIANT_VALUE']);
assert.equal(validateHierarchy().ok, true);
console.log('CANONICAL TAXONOMY CONTRACT: all checks passed');
