import fs from 'node:fs';
const read=p=>fs.readFileSync(new URL('../'+p,import.meta.url),'utf8');
const html=read('html/06-modals-social.html'), js=read('js/app/28-buyer-engagement.js'), rules=read('firestore.rules'), mode=read('html/03-modals-core.html'), product=read('js/app/07-product.js');
let pass=0,fail=0;function t(n,v){if(v){pass++;console.log('PASS '+n)}else{fail++;console.error('FAIL '+n)}}
const tabs=['overview','orders','requests','negotiations','deliveries','saved','liked','following','recent','reviews','activity','sokopay','account'];
t('existing My SokoHai surface is the single Buyer dashboard',html.includes('id="mySokoHaiModal"')&&html.includes('class="byd-shell"'));
t('all required Buyer sections exist',tabs.every(x=>html.includes(`data-byd-tab="${x}"`)));
t('Overview is default and active',html.includes('class="byd-tab active" data-byd-tab="overview"'));
t('dashboard contains no marketplace search input',!html.match(/mySokoHaiModal[\s\S]{0,12000}<input[^>]+type="search"/));
t('Kazi Buyer opens dashboard rather than duplicate marketplace mode',mode.includes("skhOpenMySokoHai('overview')"));
t('Home has a separate explicit action',html.includes('onclick="window.skhBuyerGoHome()"'));
t('Back delegates to one-level navigation',js.includes("typeof window.skhBack === 'function'"));
t('Orders are owner-filtered at query',js.includes("buyerQuery('orders','buyerId'"));
t('Requests are owner-filtered at query',js.includes("buyerQuery('requests','senderId'"));
t('Negotiations are owner-filtered at query',js.includes("buyerQuery('negotiations','buyerId'"));
t('Deliveries are owner-filtered at query',js.includes("buyerQuery('ride_requests','customerId'"));
t('Saved, likes and follows use existing relationship collections',js.includes("buyerQuery('savedProducts','userId'")&&js.includes("buyerQuery('productLikes','userId'")&&js.includes("buyerQuery('sellerFollowers','followerId'"));
t('Negotiation shortcut opens existing Chat',js.includes("typeof window.openChatWithUser === 'function'"));
t('Orders shortcut opens existing tracking/order authority',js.includes("typeof window.openOrderTracking === 'function'")&&js.includes("openBuyerOrdersModal"));
t('Delivery shortcut opens existing tracking authority',js.includes("typeof window.openRideTracking === 'function'"));
t('SokoPay shortcut opens existing SokoPay',js.includes("window.openSokoPay&&window.openSokoPay()"));
t('Notifications remain a global shortcut',js.includes("window.openNotifications&&window.openNotifications()"));
t('Chat remains a global shortcut',js.includes("window.openChatList&&window.openChatList()"));
t('empty states return to Home only',js.includes("Rudi Home")&&!js.includes('Shop Now'));
t('summary values use server counts, not sample numbers',js.includes("buyerCount('orders','buyerId')")&&js.includes("buyerCount('savedProducts','userId')")&&js.includes("buyerCount('sellerFollowers','followerId')"));
t('active commerce summaries use scoped real-time listeners',js.includes("listen('orders','buyerId'")&&js.includes("listen('ride_requests','customerId'")&&js.includes("listen('negotiations','buyerId'"));
t('recent view uses the existing central event stream',product.includes("type: 'ENTITY_VIEWED'")&&product.includes("'recommendationEvents'"));
t('recent view uses deterministic bounded IDs',product.includes("'__view__' + colName + '__' + found.id"));
t('orders rules enforce participant isolation',rules.includes('resource.data.buyerId == request.auth.uid')&&rules.includes("affectedKeys().hasAny(['buyerId','sellerId','providerId','courierId'])"));
t('requests rules enforce sender/receiver isolation',rules.includes('resource.data.senderId == request.auth.uid')&&rules.includes('resource.data.receiverId == request.auth.uid'));
t('private activity rule is owner-only except search signals',rules.includes("resource.data.type == 'search'")&&rules.includes('resource.data.userId == request.auth.uid'));
console.log(`\nBUYER DASHBOARD CONTRACT: ${pass} passed, ${fail} failed`);if(fail)process.exit(1);
