import fs from 'node:fs';import assert from 'node:assert/strict';import {chromium} from 'playwright';import {getProductSuggestions} from '../shared/product-taxonomy-bridge.mjs';
const queue=JSON.parse(fs.readFileSync('docs/taxonomy/mission/execution-queue.json')),ids=[...new Set(queue.map(x=>x.categoryId))];const b=await chromium.launch(),p=await b.newPage({viewport:{width:768,height:1000}});p.setDefaultTimeout(8000);const results=[];
try{await p.goto('http://127.0.0.1:4174');await p.waitForFunction(()=>window.previewReady);
for(const id of ids){const leaf=queue.find(x=>x.categoryId===id).leaf;try{
 await p.click('#previewSeller');await p.evaluate(()=>{skhProductBuilderReset();testDocs.clear();});await p.selectOption('#prodCategory',id);await p.selectOption('#prodSubCategory',leaf);await p.fill('#prodName',id+' custom selector test');await p.fill('#prodPrice','2000');await p.fill('#prodStock','0');await p.fill('#prodLocation','Dar');
 // An explicit seller custom selector tests builder capability, NOT category semantics.
 await p.click('#spbAddOption');await p.fill('#spbEditName','Seller Test Choice');
 const fields=await p.locator('#spbEditor input,#spbEditor textarea').evaluateAll(els=>els.map(e=>({id:e.id,type:e.type})));const valueField=fields.find(e=>/Value/.test(e.id));if(!valueField)throw Error(JSON.stringify(fields));await p.fill('#'+valueField.id,'Alpha, Beta');await p.click('#spbEditorSave');await p.click('#spbGenerate');assert.equal(await p.locator('.spb-variant').count(),2);assert.equal(await p.locator('[data-field="enabled"]:checked').count(),0);
 await p.evaluate(()=>{for(const e of document.querySelectorAll('[data-field="enabled"]')){e.checked=true;e.dispatchEvent(new Event('input',{bubbles:true}));}for(const e of document.querySelectorAll('[data-field="stock"]')){e.value=2;e.dispatchEvent(new Event('input',{bubbles:true}));}for(const [i,e] of [...document.querySelectorAll('[data-field="barcode"]')].entries()){e.value='LOCAL-'+i;e.dispatchEvent(new Event('input',{bubbles:true}));}});
 await p.locator('#spbVariants').scrollIntoViewIfNeeded();await p.screenshot({path:`docs/taxonomy/mission/screenshots/${id}-custom-variants.png`});await p.click('#spbSaveDraft');await p.waitForFunction(()=>testDocs.size===1);const before=await p.evaluate(()=>[...testDocs.values()][0].variantCombinations);assert.equal(before.length,2);for(const v of before)for(const k of ['sku','barcode','variantId','unitId','inventoryKey'])assert.ok(v[k]);await p.click('#previewEdit');await p.evaluate(()=>submitEditForm({preventDefault(){}}));const after=await p.evaluate(()=>[...testDocs.values()][0].variantCombinations);assert.deepEqual(after.map(v=>[v.variantId,v.sku,v.unitId,v.inventoryKey,v.stock]),before.map(v=>[v.variantId,v.sku,v.unitId,v.inventoryKey,v.stock]));await p.click('#previewBuyer');await p.locator('#pmVariantSelectionArea .pm-chip').filter({hasText:'Alpha'}).click();await p.locator('#pmVariantSelectionArea').scrollIntoViewIfNeeded();await p.screenshot({path:`docs/taxonomy/mission/screenshots/${id}-custom-variant-buyer.png`});results.push({categoryId:id,leaf,status:'PASS',scope:'Seller-custom selector capability only, NOT verified taxonomy variant rule',identities:before.map(v=>({variantId:v.variantId,sku:v.sku,unitId:v.unitId,inventoryKey:v.inventoryKey}))});
 }catch(e){results.push({categoryId:id,leaf,status:'FAIL',error:e.message});}fs.writeFileSync('docs/taxonomy/mission/family-variants.json',JSON.stringify(results,null,2));}
if(results.some(r=>r.status==='FAIL'))process.exitCode=1;
console.log(results.map(r=>({category:r.categoryId,status:r.status,error:r.error})));
}finally{await b.close();}
