import assert from 'node:assert/strict';
import fs from 'node:fs';
const html = fs.readFileSync(new URL('../html/09-admin-sell.html', import.meta.url), 'utf8');
const builder = fs.readFileSync(new URL('../js/app/06-product-builder.js', import.meta.url), 'utf8');
const submit = fs.readFileSync(new URL('../js/app/08-app-state.js', import.meta.url), 'utf8');
for (const id of ['spbBuilder','spbSuggestions','spbAttributes','spbOptions','spbVariants','spbFeatures','spbAdditional','spbAddAttribute','spbAddOption','spbGenerate','spbManualVariant']) assert.ok(html.includes(`id="${id}"`), `missing ${id}`);
for (const token of ['selectorType','values','filterable','variantsStructured','features','additionalInfo','generateVariants','Manual variant']) assert.ok(builder.includes(token), `missing builder token ${token}`);
for (const token of ['Generate combinations','Add variant manually']) assert.ok(html.includes(token), `missing UI label ${token}`);
for (const token of ['structuredFields','structuredProduct','skh.saveData(\'products\'']) assert.ok(submit.includes(token), `missing save bridge ${token}`);
assert.ok(fs.readFileSync(new URL('../html/21-scripts.html', import.meta.url), 'utf8').includes('js/app/06-product-builder.js'));
console.log('PRODUCT BUILDER UI CONTRACT: passed structured Add Product sections and existing save bridge checks.');
