import fs from 'node:fs';
const r=p=>fs.readFileSync(new URL('../'+p,import.meta.url),'utf8');
const html=r('html/03-modals-core.html'), roles=r('js/app/19-roles.js'), menu=r('js/app/22-printing.js'), css=r('css/36-advertiser-coming-soon.css'), rules=r('firestore.rules'), fn=r('functions/index.js');
let pass=0,fail=0;const t=(n,v)=>{if(v){pass++;console.log('PASS '+n)}else{fail++;console.error('FAIL '+n)}};
const block=roles.slice(roles.indexOf('// Advertiser Billing & Payments'));
t('Kazi includes one Advertiser entry',html.match(/id="mode-advertiser"/g)?.length===1);
t('Advertiser entry opens dedicated existing-role surface',html.includes('window.skhOpenAdvertiserDashboard && window.skhOpenAdvertiserDashboard()'));
t('account management menu includes Advertiser entry',menu.includes("['mode_advertiser','','Advertiser'"));
t('Advertiser dashboard modal exists once',html.match(/id="advertiserDashboardModal"/g)?.length===1);
t('Billing entry is visible and accessibility-disabled',html.includes('class="adv-nav-item locked" aria-disabled="true"')&&html.includes('Billing &amp; Payments'));
t('Billing professional card is disabled-styled',html.includes('class="adv-card adv-billing-card" aria-disabled="true"'));
t('locked entry provides explicit feedback rather than doing nothing',html.includes('onclick="window.skhOpenAdvertiserBillingSoon()"'));
t('Coming Soon dialog exists once',html.match(/id="advertiserBillingSoonModal"/g)?.length===1);
t('dialog contains required Swahili explanation',html.includes('Mfumo wa malipo na usimamizi wa gharama za matangazo unakuja hivi karibuni.'));
t('dialog contains Coming Soon state',html.includes('<span class="adv-coming">Coming Soon</span>'));
t('dialog has Sawa close action',html.includes('onclick="window.skhCloseAdvertiserBillingSoon()">Sawa</button>'));
t('Advertiser billing handlers do not open SokoPay',!block.includes('openSokoPay'));
t('Advertiser billing handlers do not open checkout',!block.match(/openCheckout|checkoutModal|proceedToPay/i));
t('Advertiser billing handlers do not call wallet or payment gateway',!block.match(/WalletPayment|Pesapal|paymentGateway|walletAdjust/i));
t('no advertising billing collection was introduced',!rules.match(/adBilling|adPricing|advertisingWallet|adInvoices/i)&&!roles.match(/collection\([^\n]*(adBilling|adPricing|advertisingWallet|adInvoices)/i));
t('no advertising billing Cloud Function was introduced',!fn.match(/exports\.(adBilling|adPricing|advertisingInvoice|advertisingPayment)/i));
t('visual state uses neutral disabled styling',css.includes('.adv-nav-item.locked')&&css.includes('background:#F4F6F6'));
t('responsive mobile breakpoint exists',css.includes('@media(max-width:680px)')&&css.includes('height:100dvh'));
t('small-phone breakpoint exists',css.includes('@media(max-width:360px)'));
t('Billing UI has no overflowing fixed desktop width',css.includes('width:min(92vw,450px)'));
console.log(`\nADVERTISER BILLING COMING SOON: ${pass} passed, ${fail} failed`);if(fail)process.exit(1);
